all:
  children:
    raspberries:
      hosts:
        pi2:
          ansible_host: 192.168.1.174
          ansible_user: oedc-box-02          # SSH user for pi2
        pi3:
          ansible_host: 192.168.1.178
          ansible_user: oedc-box-03          # SSH user for pi3
        # Add more Pi hosts with different SSH users here...

      vars:
        ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa  # Path to your private key
        ansible_become: yes           # Enable sudo privileges
        ansible_become_method: sudo  # Use sudo to escalate privileges

